# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

lane :installTestBuild do
    gradle(
        task: "installProdDebug"
    )
    gradle(
        task: "installProdDebugAndroidTest"
    )
end

lane :generateScreenshots do
    installTestBuild
    screengrab
end

lane :sendScreenshotsStore do |options|
    supply(
     package_name: 'your.package.name',
     skip_upload_apk: 'true',
     skip_upload_aab: 'true',
     skip_upload_metadata: 'true',
     skip_upload_changelogs: 'true',
     skip_upload_images: 'true',
     skip_upload_screenshots: 'false',
     json_key: 'path_to_your_key.json',
     version_code: options[:versionCode].to_i
    )
end