name: Generate pretty screenshots and upload them on the store

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      languages:
        description: 'List of languages'
        # Default value if no value is explicitly provided
        default: '["fr-FR","en-US"]'
        # Input has to be provided for the workflow to run
        required: true
      versionCode:
        description: 'Last version code of the app'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  upload-screenshots-store:
    name: Generate pretty screenshots and upload them on the store
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          # Use version 8 as some tests return different results with JDK11
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            .gradle
          key: ${{ runner.os }}-gradle-pretty-screenshots-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-pretty-screenshots-
      - name: Cache Gradle wrapper
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
      - name: generate final screenshots
        run: ./gradlew generateFinalScreenshots -PapiKey="${{ secrets.YOUR_ABYSSALE_API_KEY }}" -Pcountries=${{ github.event.inputs.languages }}
      - name: dowlnload JSON key file
        run: ./gradlew downloadAuthJsonStore -PstoreAuthKey="${{ secrets.PATH_TO_YOUR_JSON_KEY_FILE }}"
      - name: upload screenshots on store
        run: fastlane sendScreenshotsStore versionCode:${{ github.event.inputs.versionCode }}
      - name: Upload screenshots in atrifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: screenshots
          path: ./**/fastlane/metadata/**.jpeg