name: Generate screenshots

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      languages:
        description: 'List of languages'
        # Default value if no value is explicitly provided
        default: '["fr-FR","fr-BE","de-DE","it-IT"]'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  raw-screenshots:
    name: Generate raw screenshots
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-rw-screenshots-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-rw-screenshots-

      - name: Cache Gradle wrapper
        uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
      - name: create AVD and generate raw screenshots
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          arch: x86
          profile: 24
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          sdcard-path-or-size: 1000M
          script: sed -i -e 's/LOCALES/${{ github.event.inputs.languages }}/' "fastlane/Screengrabfile" && fastlane generateScreenshots
      - name: rename raw screenshots
        run: ./gradlew processRawScreenshots
      - name: Upload screenshots in atrifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: screenshots
          path: fastlane/

  generate-pretty-screenshots:
    name: Generate pretty screenshots
    runs-on: ubuntu-latest
    needs: raw-screenshots
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-rw-screenshots-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-rw-screenshots-

      - name: Cache Gradle wrapper
        uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - uses: actions/download-artifact@master
        with:
          name: screenshots
          path: fastlane/

      - name: generate pretty screenshots
        run: ./gradlew generateFinalScreenshots -PapiKey="${{ secrets.YOUR_ABYSSALE_TOKEN }}" -Pcountries=${{ github.event.inputs.languages }}

      - name: Upload screenshots in atrifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: finalScreenshots
          path: fastlane/

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx6g -Dfile.encoding=UTF-8" -Dorg.gradle.vfs.watch=false -Dkapt.incremental.apt=false -Dandroid.databinding.incremental=false
